server:
  port: 8080

database:
  driver: postgres
  host: localhost
  port: 5432
  user: dbuser
  password: dbpassword
  name: database_name
  charset: utf8mb4
  max_idle_conns: 20
  max_open_conns: 200

# database:
#   driver: mysql
#   host: localhost
#   port: 3306
#   user: dbuser
#   password: dbpassword
#   name: database_name
#   charset: utf8mb4
#   max_idle_conns: 20
#   max_open_conns: 200

jwt:
  secret: "super-secret-prod-key"
  expire_hours: 72

google:
  ios:
    client_id: "your-ios-google-client-id"
    client_secret: "your-ios-google-client-secret"
    redirect_urls:
      - "com.yourapp.scheme://oauth/callback"  # iOS应用深链接
  web:
    client_id: "your-web-google-client-id"
    client_secret: "your-web-google-client-secret"
    redirect_urls:
      - "http://localhost:5173/auth/callback"  # 本地开发Web应用
      - "https://yourapp.com/auth/callback"    # 生产环境Web应用

wechat:
  web:
    appid: "your-wechat-web-appid"
    secret: "your-wechat-web-secret"
  app:
    appid: "your-wechat-app-appid"
    secret: "your-wechat-app-secret"

# 邮件服务配置
email:
  provider: "sendgrid"  # sendgrid 或 smtp
  sendgrid_api_key: ""  # SendGrid API Key
  from_email: "noreply@yourapp.com"
  from_name: "YourApp"
  smtp:  # 当provider为smtp时使用
    host: "smtp.gmail.com"
    port: 587
    username: ""
    password: ""
    tls: true

# Redis配置 (用于存储验证码)
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

ai:
  openai_api_key: ""
  moonshot_api_url: "https://api.moonshot.cn/v1"
  moonshot_api_key: ""
  deepseek_api_url: "https://api.deepseek.com"
  deepseek_api_key: ""

# 微信云托管相关配置
wechat_cloudrun:
  storage:
    cos_bucket: "your-wechat-cloudrun-cos-bucket"
    cos_region: "ap-shanghai"
