server:
  port: 8080

database:
  driver: postgres
  host: localhost
  port: 5432
  user: dbuser
  password: dbpassword
  name: database_name
  charset: utf8mb4
  max_idle_conns: 20
  max_open_conns: 200

# database:
#   driver: mysql
#   host: localhost
#   port: 3306
#   user: dbuser
#   password: dbpassword
#   name: database_name
#   charset: utf8mb4
#   max_idle_conns: 20
#   max_open_conns: 200

jwt:
  secret: "super-secret-prod-key"
  expire_hours: 72

ai:
  openai_api_key: ""
  moonshot_api_url: "https://api.moonshot.cn/v1"
  moonshot_api_key: ""
  deepseek_api_url: "https://api.deepseek.com"
  deepseek_api_key: ""

google:
  ios:
    client_id: "your-ios-google-client-id"
    client_secret: "your-ios-google-client-secret"
    redirect_urls:
      - "com.yourapp.scheme://oauth/callback"  # iOS应用深链接
  web:
    client_id: "your-web-google-client-id"
    client_secret: "your-web-google-client-secret"
    redirect_urls:
      - "http://localhost:3000/auth/callback"  # 本地开发Web应用
      - "https://yourapp.com/auth/callback"    # 生产环境Web应用
